(cl:defpackage battery_simulator-msg
  (:use )
  (:export
   "<BATTERY_SIMACTION>"
   "BATTERY_SIMACTION"
   "<BATTERY_SIMACTIONFEEDBACK>"
   "BATTERY_SIMACTIONFEEDBACK"
   "<BATTERY_SIMACTIONGOAL>"
   "BATTERY_SIMACTIONGOAL"
   "<BATTERY_SIMACTIONRESULT>"
   "BATTERY_SIMACTIONRESULT"
   "<BATTERY_SIMFEEDBACK>"
   "BATTERY_SIMFEEDBACK"
   "<BATTERY_SIMGOAL>"
   "BATTERY_SIMGOAL"
   "<BATTERY_SIMRESULT>"
   "BATTERY_SIMRESULT"
  ))

